# This is a basic workflow to help you get started with Actions

name: Run Postman Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Scheduler
  schedule:
    - cron: "30 0 * * *" # Runs 6AM IST
    - cron: "00 13 * * *" # Runs 6.30PM IST

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Run-Postman-Tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          clean: true

      # Runs a single command using the runners shell
      - name: Install Node.js and npm
        uses: actions/setup-node@v6.2.0
        with:
          node-version: "22"

      # Runs a commands using the runners shell
      - name: Install newman # Installs Newman globally in VM
        run: |
          npm install -g newman

      # Runs a command using the runners shell
      - name: Install newman-html-reporter # Installs Newman globally in VM
        run: |
          npm install -g newman-reporter-htmlextra

      # Run Postman collection from command line
      - name: Run postman collection from command line
        run: |
          newman run 'Phoenix-Inwarrenty-Flow.postman_collection.json' \
          -e 'Phoenix_QA.postman_environment.json' \
          -r cli,htmlextra --reporter-html-export ./newman/index.html

      # Archieve execution report
      - name: Archive execution report
        if: always()
        uses: actions/upload-artifact@v6.0.0
        with:
          name: newman-html-report
          path: newman/*.html

      # Deploy Test Results into github pages
      - name: Deploy Test Results to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./newman/
